spring.application.name=spring_ai_phase2
server.port=8080
spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.1-flash-lite
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# Spring AI JDBC Chat Memory
# ==========================flyway implementation
spring.ai.chat.memory.repository.jdbc.initialize-schema=always